#!/usr/bin/env node
/**
 * Regenerates this skill's FinOps reference from a Postman export of the "AgriERP Product"
 * collection. Only the `FinOps` folder is read; the rest of the export (MW, Growers Portal, PDF
 * Service) is ignored because it carries literal client secrets and bearer tokens.
 *
 *   node scripts/extract.mjs [path/to/AgriERP Product.postman_collection.json]
 *
 * Default input: `AgriERP Product.postman_collection.json` at the repo root.
 * Writes (next to this script's parent):
 *   collection.finops.json   the FinOps folder only, as a standalone v2.1 collection
 *   reference/services.md    one section per request: method, path, body, notes
 *
 * Refuses to write if any FinOps request holds a literal credential (a client_secret, client_id or
 * Authorization value that is not a {{variable}}), so a secret can't leak into the skill.
 * Node >= 20, no dependencies.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const SKILL = path.resolve(import.meta.dirname, '..');
const REPO = path.resolve(SKILL, '../../..');
const input = process.argv[2] ?? path.join(REPO, 'AgriERP Product.postman_collection.json');

const collection = JSON.parse(readFileSync(input, 'utf8'));
const folder = collection.item.find((i) => i.name === 'FinOps');
if (!folder) throw new Error(`No "FinOps" folder in ${input}`);

const SECRET_KEYS = new Set(['client_secret', 'client_id', 'authorization', 'password', 'x-api-key']);
const leaks = [];
for (const item of folder.item) {
  const req = item.request;
  const pairs = [...(req.body?.urlencoded ?? []), ...(req.header ?? [])];
  for (const { key, value } of pairs) {
    const v = String(value ?? '').trim();
    if (SECRET_KEYS.has(key.toLowerCase()) && v && !/\{\{[^}]+\}\}/.test(v)) leaks.push(`${item.name}: ${key}`);
  }
}
if (leaks.length) {
  console.error(`Literal credentials in the FinOps folder, not writing:\n  ${leaks.join('\n  ')}`);
  process.exit(1);
}

const rawUrl = (u) => (typeof u === 'string' ? u : u.raw);
// Path after {{AppUrl}} — e.g. /api/services/F3AgriERPServices/F3AgriCropServices/get
const pathOf = (u) => rawUrl(u).replace(/^\{\{AppUrl\}\}/, '');
// Postman lets raw bodies carry // comments; strip whole-line ones and keep the last live body.
const liveBody = (raw = '') =>
  raw
    .split('\n')
    .filter((l) => !/^\s*\/\//.test(l))
    .join('\n')
    .trim();

writeFileSync(
  path.join(SKILL, 'collection.finops.json'),
  JSON.stringify({ info: { ...collection.info, name: 'AgriERP Product — FinOps' }, auth: collection.auth, item: [folder] }, null, 2) + '\n',
);

// Group by the service path so duplicates and mislabelled entries show up side by side.
const byPath = new Map();
for (const item of folder.item) {
  const p = pathOf(item.request.url);
  if (!byPath.has(p)) byPath.set(p, []);
  byPath.get(p).push(item.name);
}

let md = `# FinOps services (generated)

<!-- Generated by scripts/extract.mjs from the Postman "FinOps" folder. Do not hand-edit. -->

Source: \`${path.basename(input)}\`, ${folder.item.length} requests, ${byPath.size} distinct paths.
Every request is \`POST {{AppUrl}}<path>\` with \`Authorization: Bearer <token>\` (see SKILL.md),
except **Auth**, which gets the token from Microsoft Entra ID.

| # | Postman name | Operation | Path |
|---|---|---|---|
`;
folder.item.forEach((item, n) => {
  const p = pathOf(item.request.url);
  const op = p.split('/').pop();
  md += `| ${n + 1} | [${item.name}](#${n + 1}) | \`${op}\` | \`${p}\` |\n`;
});

md += `\n## Paths used by more than one request\n\n`;
const dupes = [...byPath].filter(([, names]) => names.length > 1);
md += dupes.length
  ? dupes.map(([p, names]) => `- \`${p}\`: ${names.map((n) => `"${n}"`).join(', ')}`).join('\n') + '\n'
  : '_None._\n';

folder.item.forEach((item, n) => {
  const req = item.request;
  const body = req.body ?? {};
  md += `\n<a id="${n + 1}"></a>\n## ${n + 1}. ${item.name}\n\n\`${req.method} ${rawUrl(req.url)}\`\n\n`;
  if (body.mode === 'urlencoded') {
    md += 'Form body (`application/x-www-form-urlencoded`):\n\n| Key | Value |\n|---|---|\n';
    for (const { key, value } of body.urlencoded) md += `| \`${key}\` | \`${String(value).trim()}\` |\n`;
  } else if (body.mode === 'raw') {
    const live = liveBody(body.raw);
    const commentedOut = body.raw.split('\n').filter((l) => /^\s*\/\//.test(l)).length;
    md += 'Body (`application/json`, as saved in Postman — inline `//` comments are Postman-only and must be removed before sending):\n\n```jsonc\n' + live + '\n```\n';
    if (commentedOut) md += `\n_${commentedOut} commented-out lines (earlier variants of this body) omitted; see collection.finops.json._\n`;
  }
  const tests = (item.event ?? []).filter((e) => e.listen === 'test').flatMap((e) => e.script.exec).join('\n');
  if (/environment\.set\(\s*"([^"]+)"/.test(tests)) {
    md += `\nPost-response script saves \`access_token\` into the \`${tests.match(/environment\.set\(\s*"([^"]+)"/)[1]}\` environment variable.\n`;
  }
});

writeFileSync(path.join(SKILL, 'reference', 'services.md'), md);
console.log(`Wrote collection.finops.json and reference/services.md (${folder.item.length} requests, ${byPath.size} paths).`);
