#!/usr/bin/env node
/**
 * Regenerates reference/<Tag>.md and the tag index inside SKILL.md from the Swagger 2.0 spec
 * (NSwag export of the VannBrosPhaseTwo QA API).
 *
 *   node scripts/generate.mjs [path/to/openapi.json]
 *
 * Default spec: <skill>/openapi.json. No dependencies.
 *
 * - One file per tag, operations in spec order. Each carries the definitions its operations
 *   reference, SCHEMA_DEPTH levels deep, with `allOf` flattened; deeper types link into
 *   reference/_schemas.md, which holds every definition.
 * - Only files that carry the GENERATED marker are ever deleted (tags that disappeared).
 * - The index lives between the INDEX markers in SKILL.md; the rest of SKILL.md is hand-written.
 * - One-line tag summaries come from tag-summaries.json; a new tag gets an auto summary and a
 *   warning so someone writes a real one.
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const SKILL_DIR = path.resolve(import.meta.dirname, '..');
const SPEC = path.resolve(process.argv[2] ?? path.join(SKILL_DIR, 'openapi.json'));
const REF_DIR = path.join(SKILL_DIR, 'reference');
const SKILL_MD = path.join(SKILL_DIR, 'SKILL.md');
const SUMMARIES = path.join(SKILL_DIR, 'scripts/tag-summaries.json');

const SCHEMAS_FILE = '_schemas.md';
// Tag files inline schemas this many levels deep (1 = body/param schemas, 2 = their direct
// nested types). Deeper types link into _schemas.md: the entity graph is densely connected, and
// a full closure put ~260 schemas (240 KB) into single tag files.
const SCHEMA_DEPTH = Number(process.env.SCHEMA_DEPTH ?? 2);
const MARKER = '<!-- GENERATED by scripts/generate.mjs — do not edit by hand; run scripts/refresh.sh -->';
const INDEX_BEGIN = '<!-- BEGIN TAG INDEX (generated) -->';
const INDEX_END = '<!-- END TAG INDEX -->';
const METHODS = ['get', 'post', 'put', 'patch', 'delete', 'head', 'options'];

const raw = readFileSync(SPEC, 'utf8');
const spec = JSON.parse(raw);
if (spec.swagger !== '2.0') throw new Error(`expected a Swagger 2.0 document, got ${spec.swagger ?? spec.openapi}`);
const defs = spec.definitions ?? {};
const summaries = existsSync(SUMMARIES) ? JSON.parse(readFileSync(SUMMARIES, 'utf8')) : {};

const refName = (ref) => ref.replace(/^#\/definitions\//, '');
const anchor = (name) => `schema-${name.toLowerCase()}`;
// Names rendered in the file being written; anything else links to the shared catalogue.
let local = null;
const schemaLink = (n) => `[${n}](${!local || local.has(n) ? '' : SCHEMAS_FILE}#${anchor(n)})`;
const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');

function typeOf(s) {
  if (!s) return '—';
  if (s.$ref) {
    return schemaLink(refName(s.$ref));
  }
  if (s.allOf?.length === 1) return typeOf(s.allOf[0]);
  switch (s.type) {
    case 'array':
      return `${typeOf(s.items)}[]`;
    case 'integer':
    case 'number':
      return s.format ?? s.type;
    case 'string':
      return s.format ? `string (${s.format})` : 'string';
    case 'object':
      if (s.additionalProperties) {
        return `map<string, ${s.additionalProperties === true ? 'any' : typeOf(s.additionalProperties)}>`;
      }
      return s.properties ? 'object (inline)' : 'object';
    default:
      return s.type ?? 'any';
  }
}

/** Definition names reachable from a schema within `depth` levels (shallowest level wins). */
function collectRefs(s, out, depth) {
  if (!s || typeof s !== 'object' || depth < 1) return;
  if (Array.isArray(s)) return s.forEach((x) => collectRefs(x, out, depth));
  if (typeof s.$ref === 'string') {
    const n = refName(s.$ref);
    if ((out.get(n) ?? 0) < depth) {
      out.set(n, depth);
      // allOf bases are part of the type itself, not a nesting level.
      for (const b of defs[n]?.allOf ?? []) collectRefs(b, out, depth);
      collectRefs({ ...defs[n], allOf: undefined }, out, depth - 1);
    }
  }
  for (const [k, v] of Object.entries(s)) if (k !== '$ref') collectRefs(v, out, depth);
}

/** Flatten `allOf` into one property list; inherited fields remember where they came from. */
function flatten(s, from = null, seen = new Set()) {
  const props = [];
  const required = new Set();
  const bases = [];
  const add = (part, origin) => {
    if (part.$ref) {
      const n = refName(part.$ref);
      if (seen.has(n)) return;
      seen.add(n);
      if (!origin) bases.push(n);
      const inner = flatten(defs[n] ?? {}, origin ?? n, seen);
      props.push(...inner.props);
      inner.required.forEach((r) => required.add(r));
      return;
    }
    for (const sub of part.allOf ?? []) add(sub, origin);
    for (const r of part.required ?? []) required.add(r);
    for (const [name, p] of Object.entries(part.properties ?? {})) props.push({ name, schema: p, from: origin });
  };
  add(s, from);
  return { props, required, bases };
}

function renderSchema(name) {
  const s = defs[name];
  const lines = [`<a id="${anchor(name)}"></a>`, `### ${name}`, ''];
  if (!s) return [...lines, '_Referenced but not defined in the spec._', ''];
  if (s.description) lines.push(s.description, '');
  if (Array.isArray(s.enum)) {
    const names = s['x-enumNames'] ?? [];
    lines.push(`Enum (${s.type}). Send the **value**.`, '', '| Value | Name |', '|---|---|');
    s.enum.forEach((v, i) => lines.push(`| \`${v}\` | ${cell(names[i] ?? '')} |`));
    return [...lines, ''];
  }
  const { props, required, bases } = flatten(s);
  if (!props.length) return [...lines, `Type: ${typeOf(s)}. No properties declared.`, ''];
  if (bases.length) lines.push(`Extends ${bases.map(schemaLink).join(', ')} (inherited fields included below).`, '');
  const req = props.filter((p) => required.has(p.name)).map((p) => `\`${p.name}\``);
  lines.push(`Required: ${req.length ? req.join(', ') : '_none_'}`, '');
  lines.push('| Field | Type | Required | Notes |', '|---|---|---|---|');
  for (const p of props) {
    const notes = [];
    if (p.from) notes.push(`from ${p.from}`);
    if (p.schema.description) notes.push(p.schema.description);
    if (p.schema.minLength !== undefined) notes.push(`minLength ${p.schema.minLength}`);
    if (p.schema.maxLength !== undefined) notes.push(`maxLength ${p.schema.maxLength}`);
    if (p.schema['x-deprecated']) notes.push(`deprecated${p.schema['x-deprecatedMessage'] ? `: ${p.schema['x-deprecatedMessage']}` : ''}`);
    lines.push(`| \`${p.name}\` | ${cell(typeOf(p.schema))} | ${required.has(p.name) ? 'yes' : ''} | ${cell(notes.join('; '))} |`);
  }
  return [...lines, ''];
}

function renderParams(params) {
  const nonBody = params.filter((p) => p.in !== 'body');
  if (!nonBody.length) return ['Parameters: _none_', ''];
  const lines = ['| Param | In | Type | Required | Notes |', '|---|---|---|---|---|'];
  for (const p of nonBody) {
    const notes = [];
    if (p.required !== true && p['x-nullable'] === false) notes.push('non-nullable (omitted → server default, e.g. 0/false)');
    if (p.default !== undefined) notes.push(`default \`${JSON.stringify(p.default)}\``);
    if (p.collectionFormat === 'multi') notes.push('array: repeat the key (`?K=1&K=2`)');
    else if (p.collectionFormat) notes.push(`array: ${p.collectionFormat}`);
    if (p.description) notes.push(p.description);
    lines.push(`| \`${p.name}\` | ${p.in} | ${cell(typeOf(p))} | ${p.required ? 'yes' : ''} | ${cell(notes.join('; '))} |`);
  }
  return [...lines, ''];
}

function renderOperation(op) {
  const { method, route, o } = op;
  const lines = [`<a id="${op.anchor}"></a>`, `### ${method.toUpperCase()} \`${route}\``, ''];
  const meta = [`operationId \`${o.operationId ?? '—'}\``];
  if (o.deprecated) meta.push('**deprecated**');
  if (o.summary) meta.push(o.summary);
  lines.push(meta.join(' · '), '');
  if (o.description) lines.push(o.description, '');
  const params = o.parameters ?? [];
  lines.push(...renderParams(params));
  const body = params.find((p) => p.in === 'body');
  if (body) {
    const ct = (o.consumes ?? ['application/json'])[0];
    lines.push(`Request body \`${body.name}\` (${ct})${body.required ? ', **required**' : ''}: ${typeOf(body.schema)}`, '');
  } else {
    lines.push('Request body: _none_', '');
  }
  const resp = Object.entries(o.responses ?? {}).map(([code, r]) => {
    const t = r.schema?.type === 'file' ? 'body not described (spec says `file`)' : r.schema ? typeOf(r.schema) : 'no schema';
    return `\`${code}\` ${t}`;
  });
  lines.push(`Responses: ${resp.join('; ') || '_none declared_'}`, '');
  return lines;
}

// Group operations by tag, in spec order.
const byTag = new Map();
const usedAnchors = new Set();
for (const [route, item] of Object.entries(spec.paths ?? {})) {
  const shared = item.parameters ?? [];
  for (const method of METHODS) {
    const o = item[method];
    if (!o) continue;
    const merged = { ...o, parameters: [...shared.filter((s) => !(o.parameters ?? []).some((p) => p.name === s.name && p.in === s.in)), ...(o.parameters ?? [])] };
    const tag = o.tags?.[0] ?? 'Untagged';
    let a = `op-${(o.operationId ?? `${method}-${route}`).toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
    while (usedAnchors.has(a)) a += '-x';
    usedAnchors.add(a);
    if (!byTag.has(tag)) byTag.set(tag, []);
    byTag.get(tag).push({ method, route, o: merged, anchor: a });
  }
}
const tags = [...byTag.keys()].sort((a, b) => a.localeCompare(b, 'en', { sensitivity: 'base' }));

const summaryOf = (tag) => {
  if (summaries[tag]) return summaries[tag];
  console.warn(`warning: no summary for tag "${tag}" — add one to scripts/tag-summaries.json`);
  const ops = byTag.get(tag);
  return `${ops.length} operation(s) under \`${ops[0].route.split('/').slice(0, 3).join('/')}\` (auto summary).`;
};

mkdirSync(REF_DIR, { recursive: true });
const written = new Set();
let totalOps = 0;
for (const tag of tags) {
  const ops = byTag.get(tag);
  totalOps += ops.length;
  const refMap = new Map();
  for (const { o } of ops) for (const p of o.parameters) collectRefs(p.schema ?? p, refMap, SCHEMA_DEPTH);
  const refs = new Set(refMap.keys());
  local = refs;
  const out = [
    MARKER,
    `# ${tag}`,
    '',
    summaryOf(tag),
    '',
    `${ops.length} operation(s). Base URL \`https://${spec.host}\`; every call needs \`Authorization: Bearer <token>\` (see ../SKILL.md).`,
    '',
    '## Operations',
    '',
    '| Method | Path | operationId |',
    '|---|---|---|',
    ...ops.map((op) => `| ${op.method.toUpperCase()} | [\`${op.route}\`](#${op.anchor}) | ${op.o.operationId ?? ''}${op.o.deprecated ? ' (deprecated)' : ''} |`),
    '',
    ...ops.flatMap(renderOperation),
    '## Schemas',
    '',
    `Types used by these operations, ${SCHEMA_DEPTH} level(s) deep. Links into \`${SCHEMAS_FILE}\` are deeper types; grep that file for \`schema-<name>\` rather than reading it whole.`,
    '',
  ];
  if (!refs.size) out.push('_No schemas referenced._', '');
  for (const n of [...refs].sort()) out.push(...renderSchema(n));
  const file = `${tag}.md`;
  writeFileSync(path.join(REF_DIR, file), out.join('\n').replace(/\n+$/, '\n'));
  written.add(file);
}

// Shared catalogue: every definition.
local = null;
writeFileSync(
  path.join(REF_DIR, SCHEMAS_FILE),
  [
    MARKER,
    '# Schema catalogue',
    '',
    `All ${Object.keys(defs).length} definitions in the spec, \`allOf\` flattened. Large: find one with \`grep -n 'id="schema-<lowercase name>"' ${SCHEMAS_FILE}\` and read from there.`,
    '',
    ...Object.keys(defs).sort().flatMap(renderSchema),
  ].join('\n').replace(/\n+$/, '\n'),
);
written.add(SCHEMAS_FILE);

for (const f of readdirSync(REF_DIR)) {
  if (!f.endsWith('.md') || written.has(f)) continue;
  const p = path.join(REF_DIR, f);
  if (readFileSync(p, 'utf8').startsWith(MARKER)) {
    unlinkSync(p);
    console.log(`removed stale reference/${f}`);
  }
}

// Tag index in SKILL.md.
const sha = createHash('sha256').update(raw).digest('hex').slice(0, 12);
const index = [
  INDEX_BEGIN,
  `_${tags.length} tags · ${totalOps} operations · ${Object.keys(spec.paths).length} paths · ${Object.keys(defs).length} definitions · spec sha256 \`${sha}\`_`,
  '',
  '| Tag | Ops | What it covers |',
  '|---|---|---|',
  ...tags.map((t) => `| [${t}](reference/${t}.md) | ${byTag.get(t).length} | ${cell(summaryOf(t))} |`),
  INDEX_END,
].join('\n');
if (existsSync(SKILL_MD)) {
  const md = readFileSync(SKILL_MD, 'utf8');
  const i = md.indexOf(INDEX_BEGIN);
  const j = md.indexOf(INDEX_END);
  if (i < 0 || j < i) throw new Error(`SKILL.md has no ${INDEX_BEGIN} … ${INDEX_END} block to replace`);
  writeFileSync(SKILL_MD, md.slice(0, i) + index + md.slice(j + INDEX_END.length));
} else {
  console.warn('warning: SKILL.md missing; index not written');
}

console.log(`generated ${tags.length} reference files (${totalOps} operations) from ${path.relative(process.cwd(), SPEC)}`);
