import { readFileSync, writeFileSync } from 'fs';
import path from 'path';
import { test, expect } from '@playwright/test';
import { routeUrl, routes } from '../constants/routes';
import { CREDENTIALS_FILE } from '../helpers/credentials';
import { classifyBlocker, signIn, type SignInBlocker } from '../helpers/signIn';
import { routeGoogleMapsViaNode } from '../helpers/googleMaps';

/**
 * Triage which QA accounts the suite can actually use.
 *
 * Tagged `@triage` and excluded from normal runs — it attempts a sign-in per account, which is
 * slow and not something to do on every suite run. Run it deliberately:
 *
 *     pnpm triage:accounts
 *
 * Why it exists: the 45 permission-scoped web cases need ONE working non-admin session, and
 * `.auth/credentials.json` holds 31 accounts of unknown state. Two were tested by hand — one
 * with an expired password, one needing MFA enrolment — but the admin account signs in
 * unattended, so the MFA policy is clearly not tenant-wide. Rather than assume the rest are
 * blocked, this classifies every account and writes the result to
 * `test-plans/ACCOUNT-TRIAGE.md`.
 *
 * It is strictly read-only with respect to the accounts: it attempts a sign-in with the
 * password already on file and classifies whatever screen comes back. It never changes a
 * password and never enrols a second factor.
 */

interface Account {
  username: string;
  password: string;
}

/** `usable` = signed in unattended and reached the app. Everything else comes from the
 *  shared sign-in classifier, so the vocabulary cannot drift from `auth.setup.ts`. */
type Outcome = 'usable' | SignInBlocker | 'unknown';

function loadAccounts(): Account[] {
  const raw = JSON.parse(readFileSync(CREDENTIALS_FILE, 'utf-8')) as Record<string, unknown>;
  const accounts: Account[] = [];
  const push = (entry: unknown) => {
    const candidate = entry as Partial<Account>;
    if (candidate?.username && candidate?.password) {
      accounts.push({ username: candidate.username, password: candidate.password });
    }
  };
  for (const [key, value] of Object.entries(raw)) {
    if (key === '_unassigned') (value as unknown[]).forEach(push);
    else if (!key.startsWith('_')) push(value);
  }
  // De-duplicate: an account can be both role-assigned and left in _unassigned.
  return [...new Map(accounts.map((a) => [a.username, a])).values()];
}

const mask = (username: string) => {
  const [local, domain] = username.split('@');
  return domain ? `${local}@${domain.split('.')[0]}…` : local;
};

test.describe('@triage QA account triage', () => {
  test.describe.configure({ mode: 'serial', timeout: 20 * 60 * 1000 });

  test('classify every account in the credentials file', async ({ browser }, testInfo) => {
    const accounts = loadAccounts();
    expect(accounts.length, 'no accounts in .auth/credentials.json').toBeGreaterThan(0);

    const results: Array<{ username: string; outcome: Outcome; note: string }> = [];

    for (const account of accounts) {
      // A fresh context per account: a leftover session would short-circuit the next sign-in.
      const context = await browser.newContext();
      await routeGoogleMapsViaNode(context);
      const page = await context.newPage();
      let outcome: Outcome = 'unknown';
      let note = '';

      try {
        // The SAME flow the setup uses — see helpers/signIn.ts for why this must not be a
        // second copy. It never throws; whatever screen it leaves behind is classified below.
        await signIn(page, account, (reason) => {
          note = reason.slice(0, 90);
        });

        const blocker = await classifyBlocker(page);
        if (blocker) {
          outcome = blocker;
        } else {
          const reached = await page
            .waitForURL(`${routeUrl(routes.maps.root)}**`, { timeout: 60_000 })
            .then(() => true)
            .catch(() => false);
          outcome = reached ? 'usable' : 'unknown';
          if (!reached && !note) note = `stopped at ${page.url().replace(/\?.*$/, '')}`;
        }
      } catch (error) {
        note = (error as Error).message.split('\n')[0].slice(0, 90);
      } finally {
        await context.close();
      }

      results.push({ username: account.username, outcome, note });
      // eslint-disable-next-line no-console
      console.log(`[triage] ${mask(account.username).padEnd(34)} ${outcome}${note ? ` (${note})` : ''}`);
    }

    // Write the report next to the other test-plan documents.
    const usable = results.filter((r) => r.outcome === 'usable');
    const lines = [
      '# QA account triage',
      '',
      '> Generated by `pnpm triage:accounts`. Do not edit by hand.',
      '> Attempts one sign-in per account in `.auth/credentials.json` and classifies the result.',
      '> Read-only: no password is changed and no second factor is enrolled.',
      '',
      `Accounts checked: **${results.length}** · usable: **${usable.length}**`,
      '',
      '| Account | Outcome | Note |',
      '|---|---|---|',
      ...results.map((r) => `| ${mask(r.username)} | ${r.outcome} | ${r.note || ''} |`),
      '',
      '## What "usable" means',
      '',
      'The account signed in unattended and reached `/maps`. Assign one to a role in',
      '`.auth/credentials.json` and bootstrap it with `AUTH_ROLES=<role> pnpm auth:qa` to unblock',
      'the permission-scoped cases. See ACCOUNTS.md for which roles the workbook needs.',
      '',
    ];
    const report = path.join(testInfo.project.testDir, '..', 'test-plans', 'ACCOUNT-TRIAGE.md');
    writeFileSync(report, lines.join('\n'));

    // eslint-disable-next-line no-console
    console.log(`[triage] ${usable.length} of ${results.length} accounts usable -> ${report}`);
  });
});
