/**
 * Coverage report: which smoke-checklist rows the automated suite actually covers.
 *
 *     pnpm smoke:coverage          # print the table
 *     pnpm smoke:coverage:write    # also refresh test-plans/SMOKE-COVERAGE.md
 *
 * The smoke counterpart of `coverage.mts`. Specs declare coverage with a tag in the test
 * title, using the IDs minted by `extract-smoke.py` into `test-plans/catalog/smoke-cases.json`:
 *
 *     test('@SMK:MP-01 Maps Control shows Upcoming Work Orders', ...)            // full
 *     test('@TC-partial:ST-001 @SMK-partial:US-03 the User Settings page ...', ...) // partial
 *
 * Same rules as the regression report: `@SMK:` means the test asserts the whole checklist
 * row, `@SMK-partial:` means part of it is still checked by hand, and partials do NOT count
 * towards the covered percentage. A test may carry `@TC` and `@SMK` tags together when one
 * test serves both the regression workbook and the smoke checklist.
 *
 * The denominator is the `web` scope only. Rows scoped `mobile`, `after-mobile` (web checks
 * of data that only mobile execution produces) and `d365` (posting verified in Dynamics)
 * are listed as manual so the scope stays visible rather than disappearing.
 */
import { readFileSync, readdirSync, writeFileSync } from 'fs';
import path from 'path';

interface SmokeCase {
  id: string;
  key: string;
  area: string;
  module: string;
  scenario: string;
  description: string;
  scope: 'web' | 'mobile' | 'after-mobile' | 'd365';
}

const ROOT = path.resolve(import.meta.dirname, '..');
const CATALOG = path.join(ROOT, 'test-plans', 'catalog', 'smoke-cases.json');
const TESTS_DIR = path.join(ROOT, 'tests');
const OUT_MD = path.join(ROOT, 'test-plans', 'SMOKE-COVERAGE.md');

function specFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return specFiles(full);
    return entry.name.endsWith('.spec.ts') ? [full] : [];
  });
}

/** Map every `@SMK:` / `@SMK-partial:` tag in the suite to the spec files that declare it. */
function taggedCases(): { full: Map<string, string[]>; partial: Map<string, string[]> } {
  const full = new Map<string, string[]>();
  const partial = new Map<string, string[]>();
  for (const file of specFiles(TESTS_DIR)) {
    const rel = path.relative(ROOT, file);
    for (const m of readFileSync(file, 'utf-8').matchAll(/@SMK(-partial)?:([A-Z]{2}-\d{2})\b/g)) {
      const target = m[1] ? partial : full;
      const files = target.get(m[2]) ?? [];
      if (!files.includes(rel)) files.push(rel);
      target.set(m[2], files);
    }
  }
  return { full, partial };
}

const catalog = JSON.parse(readFileSync(CATALOG, 'utf-8')) as {
  _meta: Record<string, unknown>;
  cases: SmokeCase[];
};
const { full: tagged, partial: taggedPartial } = taggedCases();
const byId = new Map(catalog.cases.map((c) => [c.id, c]));

// A tag that matches no checklist row is a typo or a stale ID — fail rather than ignore it.
const orphanTags = [...tagged.keys(), ...taggedPartial.keys()].filter((id) => !byId.has(id));
// A row tagged both ways is ambiguous — the full tag would silently win. Fail instead.
const doubleTagged = [...tagged.keys()].filter((id) => taggedPartial.has(id));
// Tagging a row the catalogue scopes out of the browser means one of the two is wrong.
const offScopeTags = [...tagged.keys(), ...taggedPartial.keys()].filter(
  (id) => byId.has(id) && byId.get(id)!.scope !== 'web',
);

const web = catalog.cases.filter((c) => c.scope === 'web');

interface AreaRow {
  area: string;
  module: string;
  web: number;
  covered: number;
  partial: number;
  manual: number;
}

const areas = new Map<string, AreaRow>();
for (const c of catalog.cases) {
  const row = areas.get(c.area) ?? { area: c.area, module: c.module, web: 0, covered: 0, partial: 0, manual: 0 };
  if (c.scope !== 'web') {
    row.manual += 1;
  } else {
    row.web += 1;
    if (tagged.has(c.id)) row.covered += 1;
    else if (taggedPartial.has(c.id)) row.partial += 1;
  }
  areas.set(c.area, row);
}

const coveredTotal = web.filter((c) => tagged.has(c.id)).length;
const partialTotal = web.filter((c) => !tagged.has(c.id) && taggedPartial.has(c.id)).length;
const pct = (n: number, d: number) => (d === 0 ? '—' : `${((n / d) * 100).toFixed(1)}%`);
const cell = (s: string) => s.replace(/\s*\n\s*/g, ' ').replace(/\|/g, '\\|');
const specs = (m: Map<string, string[]>, id: string) => `\`${m.get(id)!.join('`, `')}\``;

const lines: string[] = [];
lines.push('# Automation coverage vs. the Vann Brothers smoke checklist');
lines.push('');
lines.push('> Generated by `pnpm smoke:coverage:write`. Do not edit by hand.');
lines.push(
  `> Source: \`${catalog._meta.source}\`, sheet "${catalog._meta.sheet}" ` +
    `(${catalog.cases.length} rows, ${web.length} web-scoped).`,
);
lines.push('');
lines.push('Denominator is the **web** scope. Mobile rows, web checks of data only mobile');
lines.push('execution produces (*after-mobile*) and D365 posting checks are counted under');
lines.push('*Manual* rather than held against automation.');
lines.push('');
lines.push('| Area | Module | Web | Covered | Partial | Not automated | % | Manual |');
lines.push('|---|---|---:|---:|---:|---:|---:|---:|');
for (const row of areas.values()) {
  lines.push(
    `| ${row.area} | ${row.module} | ${row.web} | ${row.covered} | ${row.partial} ` +
      `| ${row.web - row.covered - row.partial} | ${pct(row.covered, row.web)} | ${row.manual} |`,
  );
}
lines.push(
  `| **TOTAL** | | **${web.length}** | **${coveredTotal}** | **${partialTotal}** ` +
    `| **${web.length - coveredTotal - partialTotal}** | **${pct(coveredTotal, web.length)}** ` +
    `| **${catalog.cases.length - web.length}** |`,
);
lines.push('');
lines.push('## Fully covered rows');
lines.push('');
lines.push('| ID | Scenario | Description | Spec |');
lines.push('|---|---|---|---|');
for (const c of web.filter((x) => tagged.has(x.id))) {
  lines.push(`| ${c.id} | ${cell(c.scenario)} | ${cell(c.description)} | ${specs(tagged, c.id)} |`);
}
lines.push('');
lines.push('## Partially covered rows');
lines.push('');
lines.push('The flow is automated but part of the row is still checked by hand. Closing a');
lines.push('partial is usually cheaper than automating a new row.');
lines.push('');
lines.push('| ID | Scenario | Description | Spec |');
lines.push('|---|---|---|---|');
for (const c of web.filter((x) => !tagged.has(x.id) && taggedPartial.has(x.id))) {
  lines.push(`| ${c.id} | ${cell(c.scenario)} | ${cell(c.description)} | ${specs(taggedPartial, c.id)} |`);
}
lines.push('');
lines.push('## Not yet automated');
lines.push('');
lines.push('| ID | Scenario | Description |');
lines.push('|---|---|---|');
for (const c of web.filter((x) => !tagged.has(x.id) && !taggedPartial.has(x.id))) {
  lines.push(`| ${c.id} | ${cell(c.scenario)} | ${cell(c.description)} |`);
}
lines.push('');

const report = lines.join('\n');
console.log(report);

if (orphanTags.length) console.error(`\n@SMK tags matching no checklist row: ${orphanTags.join(', ')}`);
if (doubleTagged.length) console.error(`\nRows tagged both @SMK: and @SMK-partial:, pick one: ${doubleTagged.join(', ')}`);
if (offScopeTags.length) console.error(`\n@SMK tags on rows not scoped web: ${offScopeTags.join(', ')}`);

if (process.argv.includes('--write')) {
  writeFileSync(OUT_MD, report);
  console.log(`\nWrote ${path.relative(ROOT, OUT_MD)}`);
}

// Non-zero on a broken traceability link so CI catches it.
process.exit(orphanTags.length || doubleTagged.length || offScopeTags.length ? 1 : 0);
